#!/usr/bin/env bash

set -euo pipefail

HOME_DIR="/home/kasm-user"
WORKSPACE_DIR="${WORKSPACE_DIR:-$HOME_DIR/workers}"
CODE_SERVER_PORT="${CODE_SERVER_PORT:-51300}"
MONITOR_PORT="${MONITOR_PORT:-51301}"
SSH_PORT="${SSH_PORT:-2222}"
STARTUP_REPO_URL="${STARTUP_REPO_URL:-}"
WORKER_SSH_ENABLED="${WORKER_SSH_ENABLED:-0}"
WORKER_SSH_AUTHORIZED_KEYS="${WORKER_SSH_AUTHORIZED_KEYS:-${WORKER_SSH_AUTHORIZED_KEY:-}}"
WORKER_SSH_PASSWORD="${WORKER_SSH_PASSWORD:-}"
WORKER_COMPUTER_USE_ENABLED="${WORKER_COMPUTER_USE_ENABLED:-0}"
WORKER_COMPUTER_USE_EXTRA_SETUP_SCRIPT="${WORKER_COMPUTER_USE_EXTRA_SETUP_SCRIPT:-}"
WORKER_CHROMIUM_DEBUG_PORT="${WORKER_CHROMIUM_DEBUG_PORT:-9222}"
WORKER_VNC_PASSWORD="${WORKER_VNC_PASSWORD:-}"
WORKER_VNC_PORT="${WORKER_VNC_PORT:-6901}"
WORKER_VNC_RESOLUTION="${WORKER_VNC_RESOLUTION:-1440x900x24}"
BASH_BIN="$(command -v bash)"
SETPRIV_BIN="$(command -v setpriv)"
BUN_BIN="$(command -v bun)"
CHPASSWD_BIN="$(command -v chpasswd)"
SSHD_BIN="$(command -v sshd)"
SSH_KEYGEN_BIN="$(command -v ssh-keygen)"
MONITOR_SCRIPT="/usr/local/bin/monitor.js"
COMPUTER_USE_SCRIPT="/usr/local/bin/computer-use-start"
CODEX_MCP_CONFIG_FRAGMENT="/usr/local/share/agentswarm/codex-mcp-config.toml"
BUN_PTY_LIB=""
DOCKERD_PID=""
SSHD_PID=""

if [ -f /usr/local/lib/bun-pty/librust_pty.so ]; then
  BUN_PTY_LIB="/usr/local/lib/bun-pty/librust_pty.so"
elif [ -f /usr/local/lib/bun-pty/librust_pty_arm64.so ]; then
  BUN_PTY_LIB="/usr/local/lib/bun-pty/librust_pty_arm64.so"
fi

mkdir -p /var/run /var/lib/docker /run/sshd
chown -R 1000:1000 "$HOME_DIR"

cleanup_docker_runtime_state() {
  local pid=""

  for pidfile in \
    /var/run/docker.pid \
    /var/run/docker/containerd/containerd.pid \
    /var/run/containerd/containerd.pid
  do
    if [ ! -f "$pidfile" ]; then
      continue
    fi

    pid="$(cat "$pidfile" 2>/dev/null || true)"

    if [ -n "$pid" ] && kill -0 "$pid" >/dev/null 2>&1; then
      case "$(ps -p "$pid" -o comm= 2>/dev/null | tr -d '[:space:]')" in
        dockerd|containerd)
          kill "$pid" >/dev/null 2>&1 || true
          wait "$pid" 2>/dev/null || true
          ;;
      esac
    fi

    rm -f "$pidfile"
  done

  pkill -x containerd >/dev/null 2>&1 || true
  pkill -x dockerd >/dev/null 2>&1 || true
}

start_dockerd_if_needed() {
  if docker info >/dev/null 2>&1; then
    return 0
  fi

  cleanup_docker_runtime_state

  if docker info >/dev/null 2>&1; then
    return 0
  fi

  dockerd \
    --host=unix:///var/run/docker.sock \
    --storage-driver=vfs \
    >/tmp/dockerd.log 2>&1 &
  DOCKERD_PID=$!

  for _ in $(seq 1 60); do
    if docker info >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done

  echo "dockerd failed to start" >&2
  cat /tmp/dockerd.log >&2 || true
  exit 1
}

setup_vscode_remote_ssh_compat() {
  local managed_env_file="$HOME_DIR/.agentswarm-shell-env"
  local bash_profile_file="$HOME_DIR/.bash_profile"
  local zshenv_file="$HOME_DIR/.zshenv"
  local vscode_env_dir="$HOME_DIR/.vscode-server"
  local vscode_env_file="$vscode_env_dir/server-env-setup"
  local source_line="[ -f \"$managed_env_file\" ] && . \"$managed_env_file\""

  mkdir -p "$vscode_env_dir" /run/current-system/sw/bin /run/current-system/sw/libexec /usr/libexec

  [ -x /bin/sh ] || ln -sf "$(command -v sh)" /bin/sh
  [ -x /usr/bin/env ] || ln -sf "$(command -v env)" /usr/bin/env
  [ -x /usr/bin/bash ] || ln -sf "$BASH_BIN" /usr/bin/bash

  if command -v ssh >/dev/null 2>&1; then
    ln -sf "$(command -v ssh)" /run/current-system/sw/bin/ssh
  fi
  if command -v scp >/dev/null 2>&1; then
    ln -sf "$(command -v scp)" /run/current-system/sw/bin/scp
  fi
  if command -v sftp >/dev/null 2>&1; then
    ln -sf "$(command -v sftp)" /run/current-system/sw/bin/sftp
  fi

  for sftp_server_bin in \
    /usr/lib/openssh/sftp-server \
    /usr/libexec/sftp-server
  do
    if [ -f "$sftp_server_bin" ]; then
      ln -sf "$sftp_server_bin" /run/current-system/sw/libexec/sftp-server
      ln -sf "$sftp_server_bin" /usr/libexec/sftp-server
      break
    fi
  done

  {
    printf '# Generated by agent-worker-entrypoint for VS Code Remote-SSH.\n'
    printf 'export PATH=%q\n' "/home/kasm-user/.local/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    if [ -n "$BUN_PTY_LIB" ]; then
      printf 'export BUN_PTY_LIB=%q\n' "$BUN_PTY_LIB"
    fi
  } > "$managed_env_file"

  chmod 600 "$managed_env_file"
  chown 1000:1000 "$managed_env_file"

  touch "$zshenv_file" "$bash_profile_file"
  if ! grep -Fqx "$source_line" "$zshenv_file"; then
    printf '\n%s\n' "$source_line" >> "$zshenv_file"
  fi
  if ! grep -Fqx "$source_line" "$bash_profile_file"; then
    printf '\n%s\n' "$source_line" >> "$bash_profile_file"
  fi
  if ! grep -Fqx '[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"' "$bash_profile_file"; then
    printf '%s\n' '[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"' >> "$bash_profile_file"
  fi
  chmod 644 "$zshenv_file" "$bash_profile_file"
  chown 1000:1000 "$zshenv_file" "$bash_profile_file"

  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -eu\n'
    printf '%s\n' "$source_line"
  } > "$vscode_env_file"

  chmod 700 "$vscode_env_file"
  chown -R 1000:1000 "$vscode_env_dir"
}

configure_codex_mcp() {
  local config_file="$HOME_DIR/.codex/config.toml"
  local marker_start="# agentswarm-computer-use-mcp:start"
  local marker_end="# agentswarm-computer-use-mcp:end"
  local temp_file=""

  mkdir -p "$HOME_DIR/.codex"
  touch "$config_file"

  temp_file="$(mktemp)"
  awk -v start="$marker_start" -v end="$marker_end" '
    $0 == start { skip = 1; next }
    $0 == end { skip = 0; next }
    skip != 1 { print }
  ' "$config_file" >"$temp_file"
  mv "$temp_file" "$config_file"

  if [ "$WORKER_COMPUTER_USE_ENABLED" = "1" ] && [ -f "$CODEX_MCP_CONFIG_FRAGMENT" ]; then
    {
      printf '\n%s\n' "$marker_start"
      cat "$CODEX_MCP_CONFIG_FRAGMENT"
      printf '%s\n' "$marker_end"
    } >>"$config_file"
  fi

  chown 1000:1000 "$config_file"
}

setup_sshd() {
  local sftp_server_bin="/usr/lib/openssh/sftp-server"

  if [ "$WORKER_SSH_ENABLED" != "1" ]; then
    return 0
  fi

  mkdir -p /etc/ssh /run /run/sshd /var/empty
  chmod 755 /run /run/sshd /var/empty

  mkdir -p "$HOME_DIR/.ssh"
  chmod 700 "$HOME_DIR/.ssh"
  touch "$HOME_DIR/.ssh/authorized_keys"
  chmod 600 "$HOME_DIR/.ssh/authorized_keys"
  chown -R 1000:1000 "$HOME_DIR/.ssh"

  if [ -n "$WORKER_SSH_AUTHORIZED_KEYS" ]; then
    printf '%s\n' "$WORKER_SSH_AUTHORIZED_KEYS" > "$HOME_DIR/.ssh/authorized_keys"
    chmod 600 "$HOME_DIR/.ssh/authorized_keys"
    chown 1000:1000 "$HOME_DIR/.ssh/authorized_keys"
  fi

  if [ -z "$WORKER_SSH_AUTHORIZED_KEYS" ] && [ -n "$WORKER_SSH_PASSWORD" ]; then
    printf 'kasm-user:%s\n' "$WORKER_SSH_PASSWORD" | "$CHPASSWD_BIN"
  fi

  if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
    "$SSH_KEYGEN_BIN" -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key >/tmp/ssh-keygen.log 2>&1 || {
      cat /tmp/ssh-keygen.log >&2 || true
      return 1
    }
  fi

  if [ ! -f "$sftp_server_bin" ] && [ -f /usr/libexec/sftp-server ]; then
    sftp_server_bin="/usr/libexec/sftp-server"
  fi

  cat > /etc/ssh/sshd_config <<EOF
Port $SSH_PORT
ListenAddress 0.0.0.0
Protocol 2
HostKey /etc/ssh/ssh_host_ed25519_key
PidFile /run/sshd.pid
UsePAM no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PasswordAuthentication $([ -n "$WORKER_SSH_PASSWORD" ] && printf '%s' 'yes' || printf '%s' 'no')
AuthorizedKeysFile .ssh/authorized_keys
PermitRootLogin no
PermitEmptyPasswords no
AllowUsers kasm-user
PermitTTY yes
X11Forwarding no
AllowAgentForwarding yes
AllowTcpForwarding yes
AllowStreamLocalForwarding yes
GatewayPorts no
ClientAliveInterval 30
Subsystem sftp $sftp_server_bin
LogLevel VERBOSE
EOF

  "$SSHD_BIN" -D -e -f /etc/ssh/sshd_config >/tmp/sshd.log 2>&1 &
  SSHD_PID=$!
}

cleanup() {
  if [ -n "$SSHD_PID" ] && kill -0 "$SSHD_PID" >/dev/null 2>&1; then
    kill "$SSHD_PID" >/dev/null 2>&1 || true
    wait "$SSHD_PID" 2>/dev/null || true
  fi

  if [ -n "$DOCKERD_PID" ] && kill -0 "$DOCKERD_PID" >/dev/null 2>&1; then
    kill "$DOCKERD_PID" >/dev/null 2>&1 || true
    wait "$DOCKERD_PID" 2>/dev/null || true
  fi
}

trap cleanup EXIT INT TERM

start_dockerd_if_needed
setup_vscode_remote_ssh_compat
configure_codex_mcp
setup_sshd

if [ -f "$HOME_DIR/.agentswarm-shell-env" ]; then
  . "$HOME_DIR/.agentswarm-shell-env"
fi

exec "$SETPRIV_BIN" \
  --reuid=1000 \
  --regid=1000 \
  --init-groups \
  env \
  HOME="$HOME_DIR" \
  USER="kasm-user" \
  WORKSPACE_DIR="$WORKSPACE_DIR" \
  STARTUP_REPO_URL="$STARTUP_REPO_URL" \
  CODE_SERVER_PORT="$CODE_SERVER_PORT" \
  MONITOR_PORT="$MONITOR_PORT" \
  WORKER_COMPUTER_USE_ENABLED="$WORKER_COMPUTER_USE_ENABLED" \
  WORKER_COMPUTER_USE_EXTRA_SETUP_SCRIPT="$WORKER_COMPUTER_USE_EXTRA_SETUP_SCRIPT" \
  WORKER_CHROMIUM_DEBUG_PORT="$WORKER_CHROMIUM_DEBUG_PORT" \
  WORKER_VNC_PASSWORD="$WORKER_VNC_PASSWORD" \
  WORKER_VNC_PORT="$WORKER_VNC_PORT" \
  WORKER_VNC_RESOLUTION="$WORKER_VNC_RESOLUTION" \
  BUN_BIN="$BUN_BIN" \
  BUN_PTY_LIB="$BUN_PTY_LIB" \
  MONITOR_SCRIPT="$MONITOR_SCRIPT" \
  COMPUTER_USE_SCRIPT="$COMPUTER_USE_SCRIPT" \
  "$BASH_BIN" -lc '
    set -euo pipefail

    github_https_url_from_repo() {
      local repo_url="$1"

      if [[ "$repo_url" =~ ^git@github\.com:(.+)$ ]]; then
        printf "https://github.com/%s\n" "${BASH_REMATCH[1]}"
        return 0
      fi

      if [[ "$repo_url" =~ ^ssh://git@github\.com/(.+)$ ]]; then
        printf "https://github.com/%s\n" "${BASH_REMATCH[1]}"
        return 0
      fi

      if [[ "$repo_url" =~ ^https://github\.com/.+ ]]; then
        printf "%s\n" "$repo_url"
        return 0
      fi

      return 1
    }

    ensure_github_known_host() {
      mkdir -p "$HOME/.ssh"
      chmod 700 "$HOME/.ssh"
      touch "$HOME/.ssh/known_hosts"
      chmod 600 "$HOME/.ssh/known_hosts"

      if command -v ssh-keyscan >/dev/null 2>&1; then
        ssh-keyscan -H github.com >> "$HOME/.ssh/known_hosts" 2>/dev/null || true
      fi

      export GIT_SSH_COMMAND="${GIT_SSH_COMMAND:-ssh -o StrictHostKeyChecking=accept-new}"
    }

    configure_github_askpass() {
      if [ -z "${GITHUB_TOKEN:-}" ]; then
        return 0
      fi

      local askpass_dir="$HOME/.local/bin"
      local askpass_script="$askpass_dir/github-askpass"

      mkdir -p "$askpass_dir"

      cat > "$askpass_script" <<EOF
#!/usr/bin/env bash
case "\${1:-}" in
  *Username*github.com*)
    printf "%s\n" "\${GITHUB_USERNAME:-git}"
    ;;
  *Password*github.com*)
    printf "%s\n" "\${GITHUB_TOKEN}"
    ;;
  *)
    exit 1
    ;;
esac
EOF

      chmod 700 "$askpass_script"
      export GIT_ASKPASS="$askpass_script"
      export GIT_TERMINAL_PROMPT=0
    }

    configure_github_auth() {
      if [ -z "${GITHUB_TOKEN:-}" ]; then
        return 0
      fi

      configure_github_askpass

      if [ -n "${GITHUB_USERNAME:-}" ]; then
        git config --global credential.username "$GITHUB_USERNAME"
      fi

      git config --global core.askPass "$GIT_ASKPASS"
      git config --global credential.helper ""

      if command -v gh >/dev/null 2>&1; then
        if ! gh auth status >/dev/null 2>&1; then
          printenv GITHUB_TOKEN | gh auth login --hostname github.com --with-token >/tmp/gh-auth.log 2>&1 || cat /tmp/gh-auth.log >&2
        fi

        gh auth setup-git >/tmp/gh-auth-setup-git.log 2>&1 || cat /tmp/gh-auth-setup-git.log >&2
      fi
    }

    clone_repository() {
      local repo_url="$1"
      local destination="$2"
      local temp_dir="${destination}.tmp-clone-$$"

      rm -rf "$temp_dir"

      if [ -n "${GITHUB_TOKEN:-}" ]; then
        local https_repo_url
        if https_repo_url="$(github_https_url_from_repo "$repo_url")"; then
          configure_github_askpass

          if git clone "$https_repo_url" "$temp_dir"; then
            git -C "$temp_dir" remote set-url origin "$https_repo_url"
            mv "$temp_dir" "$destination"
            return 0
          fi

          rm -rf "$temp_dir"
          echo "GitHub token authentication failed for $https_repo_url" >&2
          return 1
        fi
      fi

      if [[ "$repo_url" =~ ^git@github\.com:.+ || "$repo_url" =~ ^ssh://git@github\.com/.+ ]]; then
        ensure_github_known_host
      fi

      if git clone "$repo_url" "$temp_dir"; then
        mv "$temp_dir" "$destination"
        return 0
      fi

      rm -rf "$temp_dir"
      return 1
    }

    if [ -n "${STARTUP_REPO_URL}" ]; then
      parent_dir="$(dirname "$WORKSPACE_DIR")"
      mkdir -p "$parent_dir"

      if [ -d "$WORKSPACE_DIR/.git" ]; then
        :
      else
        if [ -e "$WORKSPACE_DIR" ] && [ ! -d "$WORKSPACE_DIR" ]; then
          echo "workspace path exists and is not a directory: $WORKSPACE_DIR" >&2
          exit 1
        fi

        if [ -d "$WORKSPACE_DIR" ] && [ -n "$(find "$WORKSPACE_DIR" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]; then
          echo "workspace directory exists and is not empty: $WORKSPACE_DIR" >&2
          exit 1
        fi

        if [ -d "$WORKSPACE_DIR" ]; then
          rmdir "$WORKSPACE_DIR"
        fi

        if ! clone_repository "$STARTUP_REPO_URL" "$WORKSPACE_DIR"; then
          echo "failed to clone startup repository: $STARTUP_REPO_URL" >&2
          mkdir -p "$WORKSPACE_DIR"
          cat > "$WORKSPACE_DIR/.agentswarm-startup-warning.txt" <<EOF
AgentSwarm could not clone the requested startup repository:
$STARTUP_REPO_URL

The worker was created anyway and opened with an empty workspace at:
$WORKSPACE_DIR

Check container logs and GitHub credentials if this repository should have cloned successfully.
EOF
        fi
      fi
    else
      mkdir -p "$WORKSPACE_DIR"
    fi

    configure_github_auth

    if [ "$WORKER_COMPUTER_USE_ENABLED" = "1" ]; then
      sudo env \
        HOME=/root \
        WORKER_HOME_DIR="$HOME" \
        WORKSPACE_DIR="$WORKSPACE_DIR" \
        WORKER_COMPUTER_USE_ENABLED="$WORKER_COMPUTER_USE_ENABLED" \
        WORKER_COMPUTER_USE_EXTRA_SETUP_SCRIPT="$WORKER_COMPUTER_USE_EXTRA_SETUP_SCRIPT" \
        WORKER_CHROMIUM_DEBUG_PORT="$WORKER_CHROMIUM_DEBUG_PORT" \
        WORKER_VNC_PASSWORD="$WORKER_VNC_PASSWORD" \
        WORKER_VNC_PORT="$WORKER_VNC_PORT" \
        WORKER_VNC_RESOLUTION="$WORKER_VNC_RESOLUTION" \
        "$COMPUTER_USE_SCRIPT" >/tmp/computer-use.log 2>&1 &
    fi

    "$BUN_BIN" "$MONITOR_SCRIPT" >/tmp/monitor.log 2>&1 &

    cd "$WORKSPACE_DIR"
    exec code-server \
      --auth none \
      --bind-addr 0.0.0.0:${CODE_SERVER_PORT} \
      --disable-telemetry \
      "$WORKSPACE_DIR"
  '
